# Kanagawa Dragon theme for Kitty

foreground #c5c9c5
background #181616
selection_foreground #c5c9c5
selection_background #282727

# Cursor
cursor #c5c9c5
cursor_text_color #181616

# Black
color0  #181616
color8  #625e5a

# Red
color1  #c4746e
color9  #c4746e

# Green
color2  #8a9a7b
color10 #8a9a7b

# Yellow/Gold
color3  #c4b28a
color11 #c4b28a

# Blue
color4  #7fb4ca
color12 #7fb4ca

# Magenta (use teal)
color5  #8ea4a2
color13 #8ea4a2

# Cyan (use teal)
color6  #8ea4a2
color14 #8ea4a2

# White
color7  #c5c9c5
color15 #c5c9c5
