# ── Variables ────────────────────────────────────────
# App aliases used across keybinds and rules
# Change these to swap your default apps globally

$terminal = kitty
$fileManager = dolphin
$applauncher = rofi
$browser = brave
$editor  = code
$lockscreen = hyprlock 
$notify = dunst
$wallapaper = swww

