# ── Autostart ────────────────────────────────────────
# Programs launched once on Hyprland start
# Add exec-once for daemons, bars, and background services

exec-once = waybar
exec-once = dunst
exec-once = swww-daemon
exec-once = swww img ~/.config/hypr/wallpaper/background.png --transition-type fade
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
