# ── Input ────────────────────────────────────────────
# Keyboard, mouse, touchpad and gesture settings
# Touchpad gestures and sensitivity tuned for laptop use



input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
	repeat_rate = 50
	repeat_delay = 200
    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

gesture = 3, horizontal, workspace
gesture = 3, swipe, move
gesture = 4, horizontal, workspace

device {
    name = elan06fa:00-04f3:327e-touchpad
    tap-to-click = true
    tap-and-drag = true
    natural_scroll = true
    scroll_factor = 0.3
    clickfinger_behavior = true
}
