# ── Variables ────────────────────────────────────────
# App aliases used across keybinds and rules
# Change these to swap your default apps globally

$terminal = kitty
$fileManager = thunar
$applauncher = rofi -show drun
$browser = brave
$editor  = code
$lockscreen = hyprlock 
$notify = dunst
$wallapaper = swww

