# ── VeloraOS Hyprlock ────────────────────────────────

background {
    monitor =
    path = ~/.config/hypr/wallpaper/background.png
    blur_passes = 2
    blur_size = 7
    brightness = 0.6
}

input-field {
    monitor =
    size = 250, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(8a9a7b)
    inner_color = rgb(181616)
    font_color = rgb(c5c9c5)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 10
    check_color = rgb(c4b28a)
    fail_color = rgb(c4746e)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_transition = 150
    capslock_color = rgb(c4b28a)
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba(c5c9c5ff)
    font_size = 72
    font_family = JetBrains Mono
    position = 0, 200
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(9e9b93ff)
    font_size = 18
    font_family = JetBrains Mono
    position = 0, 130
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(8a9a7bff)
    font_size = 16
    font_family = JetBrains Mono
    position = 0, -80
    halign = center
    valign = center
}
